### ISSUE TITLE
Setting half degrees and getting temps with one position after decimal point

### ISSUE THREAD

**Issue by marck1991** [normen/homebridge-platform-maxcube#10]
Hi Normen,
hi all,

first of all thanks a lot Normen for this great possibility to control MAX! hardware.
I never thought I would get rid of the shitty app from the manufacturer.
Also I would like to see a donate button for spending you a few beers for the hard work.

Now my problem: 
I set the temperatures in Celsius.
In original MAX! software you can set temperatures to half degrees and wall thermostat's temperatures are shown with one position after decimal point.
In HomeKit the temperatures (SET and GET) are only shown rounded to full degrees.
Is there a possibility to change that?

**Comment by normen** [comment]
Yeah but not great interest because who can feel half a degree? If you send me a PR I'll look at it. I guess it's mainly about changing the step size in the thermostat class.
