### ISSUE TITLE
Wall thermostat showing wrong values

### ISSUE THREAD

**Issue by Unzensiert** [normen/homebridge-platform-maxcube#13]
Hallo,

My Wall Thermostat is not working correct. It shows only 1 degree temperature and heating target 31 degrees. Also if I change the values, it is reverting to this. All other devices work fine.

**Comment by normen** [comment]
Yeah, looks like theres different wall thermostat types out there, you can try if the old/other way works by pretty much reverting this change in the maxcube2 library:

https://github.com/normen/maxcube2/commit/d22d2c92ef7239b8a817368c4a32d544275e9ef4

**Comment by Unzensiert** [comment]
Sadly it is not working, even after changing this.

**Comment by Unzensiert** [comment]
deviceStatus.temp = (payload[8]>=128 ? 25.5 : 0) + payload[12] / 10;
gives me the correct temperature reading, but it is still not setting the correct target temperature and mode.

**Comment by Unzensiert** [comment]
Sorry for spamming, my wall Thermostat is working correctly like this:

function decodeDeviceWallThermostat (payload) {
  //regular device parsing, only temp is in a different location
  var deviceStatus = decodeDeviceThermostat (payload);
  deviceStatus.temp = (payload[8]>=128 ? 25.5 : 0) + payload[12] / 10;
  var off8Bin= (payload[8] >>> 0).toString(2);
  var setPoint = parseInt(((off8Bin + '').substring(1)).replace(/[^01]/gi, ''), 2);
  deviceStatus.setpoint = setPoint / 2;
  return deviceStatus;
}

**Comment by normen** [comment]
Cool, I'll keep this issue open, maybe I can add a way to switch the decode algos in both maxcube2 and homebridge-platform-maxcube via a config option. Dunno when I get around to doing this so a PR would be welcome as well.

**Comment by Unzensiert** [comment]
So i have to correct myself, the setpoint is working stock. Only this i needed:

**Comment by Unzensiert** [comment]
Of course: EQ3 - 096ac0

**Comment by maxill1** [comment]
096ac0 that seems to be a rf_address. I mean the serial you can read via MaxCube.prototype.getDeviceConfiguration(rf_address).

Mine is OEQ0812745.
{
    "rf_address": "18eb18",
    "device_type": 3,
    "serial_number": "OEQ0812745",
    "comfort_temp": 21.5,
    "eco_temp": 16.5,
    "max_setpoint_temp": 30,
    "min_setpoint_temp": 4.5,
    "temp_offset": 30.5,
    "max_valve": 80
}

**Comment by Locao9** [comment]
Hi everyone.

I think I’ve found a solution for this issue.
I’ve installed the plugin a few days bevor starting with 3 wall thermo. 2 of them showed a temperature with approx. 25 C more then they should.
After deleting and installing everything a few time only one remains with this issue.
And I thought hmm ok I’ve changed nothing really on Homebridge side.
So I deleted everything again,  deleted the wall thermos from max, unplugged the battery and started with adding them again let them config and don’t touched anything for approx 15 minutes.
After installing everything on raspberry pi again all devices are now showing the correct temperature inside Homebridge.

May it was an issue during adding them to max in the past.

May someone can confirm this.

BG Locao

**Comment by normen** [comment]
The last update for the maxcube2 library should have a fix for some thermostat devices, maybe somebody can confirm.

**Comment by normen** [comment]
I guess this is solved then
