### ISSUE TITLE
Display of the current valve position

### ISSUE THREAD

**Issue by mills1975** [normen/homebridge-platform-maxcube#14]
Hi,

first I want to thank you for great work here.
In other implementations of Maxcube (e.g. Domoticz), there is also information
available about the current position of the valves (0-100%)
Would it be possible to implement this in your plugin, too?

Best regards
Andi

**Comment by normen** [comment]
Hi & Thanks.

No, afacis HomeKit doesn't provide a Characteristic for that: https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

A custom characteristic would only be picked up by a few HomeKit apps and I suppose the use cases are too few to implement it that way.

**Comment by thorstendorn** [comment]
Really a pity. I would also be very interested in the valve position. My use case. We have a fireplace in our house and of course I am expecting, that the thermostat is closing, when the room temperature increases. However, for some reason, it does not! The measured temperature is 25, the set temperature is 21, but the radiator is hot. Something seems to be wrong. Having that confirmed by the valve position, would be great. Regards

**Comment by thorstendorn** [comment]
Characteristic "Current Position", maybe?

**Comment by mills1975** [comment]
So, I've used a workaround with Domoticz.
I added the MaxCube in Domiticz with the eQ-3 plugin for Domiticz, and
in homebridge, I'm now using the homebridge-edomoticz Plugin.
Now I have the feedbacks in HomeKit, too. 
(not in Apple Home-App, but in the Eve-App)

Best regards
Andi
