### ISSUE TITLE
Some Wallthermo shows much higher temps 

### ISSUE THREAD

**Issue by Locao9** [normen/homebridge-platform-maxcube#16]
I have installed 3 wall thermostat 1 is showing the correct temperature the other 2 showing approx. 25°C. That's very strange.
<img width="923" alt="bildschirmfoto 2018-12-30 um 10 16 55" src="https://user-images.githubusercontent.com/46258670/50545790-3c316b00-0c1c-11e9-95c9-fe3f9c7ee6c8.png">
<img width="499" alt="bildschirmfoto 2018-12-30 um 10 20 06" src="https://user-images.githubusercontent.com/46258670/50545800-81ee3380-0c1c-11e9-9e8b-c69e2bfae5ef.png">

**Comment by normen** [comment]
Read the Max! manual about the offset setting and blocking the thermostat with furniture.

**Comment by Locao9** [comment]
hi normen

I think I've wrote it may wrong.
I mean, the temperatures on the wall are identically to the temperatures inside of the max! webfrontend for all 3 devices, means measuring and forwarding to cube is ok.
But Inside the Homebridge ui as well as on Homekit app 2 of the 3 devices are approx. 25°C above what they really are. eg. "Wohnzimmer" on cube = 22,9°C and on Homebridge 48°C. 

and you are right #13 is about the same issue, sorry haven't seen it bevor and thanks for the link. 

Interesting is that after deleting and reinstalling my hole homebridge i have now 2 devices showing the correct temperature only 1 not.

Thanks for you quick response.
