### ISSUE TITLE
Thermostats going back to 5°

### ISSUE THREAD

**Issue by skatehouse** [normen/homebridge-platform-maxcube#17]
#7  up the plugin worked for months. 
Suddenly thermostats show a strange behavior. After setting Auto in homekit, thermostats are set into AUTO mode an the scheduled temperature is set.
 
A few seconds after that the thermostat is set to 5° (Target Temperature), but I haven´t changed the temperature myself. 
MaxLink is on and no other instance is connected.

Debugging shows the log pinned. 
Deleting homekit / deleting persist and accessories folder didn´t change the behaviour. :-(
It seems as Homebridge doesn´t send the correct temperature to the thermostats. 

config.json

{
    "bridge": {
        "name": "Homebridge-Maxcube",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51830,
        "pin": "031-45-154"
    },
    "plugins": [
        "homebridge-platform-maxcube",
        "homebridge-config-ui-x"
    ],
    "platforms": [
        {
            "platform": "MaxCubePlatform",
            "name": "MaxCube Platform",
            "ip": "192.168.178.30",
            "port": 62910,
            "windowsensor": true,
            "allow_wall_thermostat": true
        },
        {
            "name": "Maxcube-Config",
            "port": 8030,
            "auth": "form",
            "theme": "blue",
            "restart": "sudo systemctl restart homebridge-max",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "custom",
                "path": "/var/log/syslog",
                "command": "sudo journalctl -f -n 100 -au homebridge-max"
            },
            "platform": "config"
        }
    ],
    "accessories": []
}

I´m running out of ideas and need help urgently -.-

**Comment by skatehouse** [comment]
Connected to Max Portal now with MaxLink off i can set the temperatures to the schedule manually. 
I tried to change them, and send them again to the thermostats: and here is the clou: 
MaxSoftware doesn´t communicate with ANY thermostat:

Wohnzimmer - Wochenprogramm
Bei der Datenübertragung ist ein Fehler aufgetreten. Die Konfiguration wurde nicht übermittelt.

That definately means, that the cube doesn´t communicate with the themostats anymore -.- 

Do I have to reconfigure them all in MAX! now - or can I just reset the cube somehow????

**Comment by normen** [comment]
Yeah, was about to say that - rather sounds like an issue in your general cube setup. From my experience restarting the cube and the thermostats usually does the trick when that happens. Sometimes it also solves itself after a while. Make sure you do NOT keep the thermostats in "manual" mode for too long, that - again in my experience - seems to increase the chances of the thermostats becoming unresponsive after a while. Feel free to bug e3 / ELV about this as they never acknowledged this widespread bug.
