### ISSUE TITLE
Switch back eco mode to auto

### ISSUE THREAD

**Issue by thecael** [normen/homebridge-platform-maxcube#18]
I've got the following problem:

When I leave the house and switch my thermostat  to 'eco'-mode which is 17 deg

When I come back I switch them to "auto" but they still keep the temperature at 17 deg. It takes until the next time interval of the max software changes the the temperature to the correct value.

Can I somehow force max to set the deg that max would normally be set on auto mode at this time? (in my case 21 deg)

Beside my personal issue, great work and thank's for your effort!!!

**Comment by normen** [comment]
Quoting from the manual:

> Note that some of these work different than in Max! or on the thermostats themselves. Enabling the auto mode will for example only change the temperature if the thermostat was off before to avoid issues where scenes in HomeKit set the mode and temperature in short succession.
