### ISSUE TITLE
wall thermostats overwrites homekit temperatures

### ISSUE THREAD

**Issue by entavio** [normen/homebridge-platform-maxcube#20]
hey i am using homebridge-platform-maxcube in ibroker/yahka at the moment everything works fineexcept for one problem. as soon as the temperature of a thermostat is changed via homekit, this value is also initially received.

a short time later this value is overwritten by the (last and different) value set on the wall thermostat, with an higher priority. this means that control is not possible.

what can I do?!

**Comment by normen** [comment]
Check the README on wall thermostats
