### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by marcoschmidt79** [normen/homebridge-platform-maxcube#22]
He, after upgrade to version 2.0.3 i have a error: 

`Mai 04 16:26:08 homebridge homebridge[13522]: [4.5.2020, 16:26:08] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 858ef40e-4076-4802-9287-de32c3faa810
Mai 04 16:26:08 homebridge homebridge[13522]:     at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
Mai 04 16:26:08 homebridge homebridge[13522]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
Mai 04 16:26:08 homebridge homebridge[13522]:     at Array.filter (<anonymous>)
Mai 04 16:26:08 homebridge homebridge[13522]:     at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
Mai 04 16:26:08 homebridge homebridge[13522]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
Mai 04 16:26:08 homebridge homebridge[13522]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 04 16:26:08 homebridge homebridge[13522]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mai 04 16:26:08 homebridge homebridge[13522]:     at Module._compile (internal/modules/cjs/loader.js:1176:30)
Mai 04 16:26:08 homebridge homebridge[13522]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
Mai 04 16:26:08 homebridge homebridge[13522]:     at Module.load (internal/modules/cjs/loader.js:1040:32)
Mai 04 16:26:08 homebridge homebridge[13522]:     at Function.Module._load (internal/modules/cjs/loader.js:929:14)
Mai 04 16:26:08 homebridge homebridge[13522]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Mai 04 16:26:08 homebridge homebridge[13522]:     at internal/main/run_main_module.js:17:47`

Im go back to 1.1.4 and everything ok

**Comment by normen** [comment]
Did you have previous failed homebridge boots? Can you delete the .homebridge/persist and .homebridge/accessories folders and try again?

**Comment by normen** [comment]
Also I need more of the whole log around that error, also the steps you did before.

**Comment by marcoschmidt79** [comment]
Sorry, my english is not so good. where are you from?

persist and accessories delete is not good idea, i have 159 accessories. 

i have installed new plugin-version with npm install -g homebridge-platform-maxcube@2.0.3 and reboot the homebridge and after i have the error-message.

**Comment by normen** [comment]
I'm expecting you to be german now, sorry if that isn't the case :)

Sonst kannst Du - wenn Du dich mit Texteditoren auskennst auch versuchen die Geräte aus der cachedAccessories Datei raus zu fummeln, das is im Prinzip ne JSON, nur leider alles auf einer Zeile.

Sind bei Dir viele Geräte mit gleichem Namen? Eig wird die UUID aus Gerätname + Raumname + Funkadresse gebildet, da sollte eigentlich nix zweimal auftauchen..

**Comment by marcoschmidt79** [comment]
Ich guck gerade, zumindest die nach Update aufgelistete UUID taucht da nicht auf, die hab ich schon gesucht. Ich versuch erstmal die Versionen ab 2.0.0 jetzt und geh nochmal in die cachedA... suchen.

**Comment by marcoschmidt79** [comment]
Also das verstehe jetzt wer will, bin jetzt von der 1.1.4 Schritt für Schritt auf 2.0.3 hoch und das läuft. Echt komisch. 

`Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring Max! Link from HomeKit
Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring 1 (Büro) from HomeKit
Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring 1 (Bad) from HomeKit
Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring Thermostat 1 (Kinderzimmer Emil) from HomeKit
Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring 1 (Wohnzimmer) from HomeKit
Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring Esszimmer 2 (Esszimmer) from HomeKit
Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring 2 (Bad) from HomeKit
Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring 1 (Küche) from HomeKit
Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring Thermostat 1 (Kinderzimmer Paul) from HomeKit
Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring Esszimmer 1 (Esszimmer) from HomeKit
Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring Flur unten (Flur unten) from HomeKit
Mai 04 17:08:18 homebridge homebridge[23995]: [4.5.2020, 17:08:18] [MaxCube Platform] Restoring Flur oben (Flur oben) from HomeKit`

**Comment by normen** [comment]
Könntest Du es auch nochmal direkt probieren? Das würde helfen falls da wirklich ein Problem im PLugin ist und nicht in Deinem Setup. Kann ja sein dass da ein anderes plugin noch Kram hinterlassen hatte, eigentlich meldet die neue Version vom Plugin die Accessories ganz anders an, da sollte sich nix überschneiden.

Hast Du denn ein ganz "normales" HomeBridge und dann nachdem Du das plugin geupdated hast (wie hast Du geupdated?) neu gestartet? Oder hast Du HOOPS oder sowas wo der die Plugins vorher schon halb lädt wenn man sie installiert?

**Comment by marcoschmidt79** [comment]
Ja, ich probiers nochmal, die Gerätezuordnung und Szenen sind jetzt eh weg. :-(

**Comment by marcoschmidt79** [comment]
root@homebridge:~# npm install -g homebridge-platform-maxcube@1.1.4
+ homebridge-platform-maxcube@1.1.4
updated 2 packages in 7.213s
root@homebridge:~# 

`Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory Max! Link
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Failed to find plugin to handle accessory 1 (Büro)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory 1 (Büro)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Failed to find plugin to handle accessory 1 (Bad)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory 1 (Bad)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Failed to find plugin to handle accessory Thermostat 1 (Kinderzimmer Emil)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory Thermostat 1 (Kinderzimmer Emil)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Failed to find plugin to handle accessory 1 (Wohnzimmer)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory 1 (Wohnzimmer)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Failed to find plugin to handle accessory Esszimmer 2 (Esszimmer)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory Esszimmer 2 (Esszimmer)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Failed to find plugin to handle accessory 2 (Bad)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory 2 (Bad)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Failed to find plugin to handle accessory 1 (Küche)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory 1 (Küche)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Failed to find plugin to handle accessory Thermostat 1 (Kinderzimmer Paul)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory Thermostat 1 (Kinderzimmer Paul)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Failed to find plugin to handle accessory Esszimmer 1 (Esszimmer)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory Esszimmer 1 (Esszimmer)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Failed to find plugin to handle accessory Flur unten (Flur unten)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory Flur unten (Flur unten)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Failed to find plugin to handle accessory Flur oben (Flur oben)
Mai 04 17:19:34 homebridge homebridge[7109]: [4.5.2020, 17:19:34] Removing orphaned accessory Flur oben (Flur oben)
`

**Comment by normen** [comment]
> Ja, ich probiers nochmal, die Gerätezuordnung und Szenen sind jetzt eh weg. :-(
Da hab ich ja vorgewarnt 😇

Die Fehler sind jetzt weil die gecachten Accessories halt nicht mehr geladen werden können.. Die müssten natürlich vorher weg.. Also alles wie vorher, vlt hast ja ein backup oder so?

**Comment by marcoschmidt79** [comment]
root@homebridge:~# npm install -g homebridge-platform-maxcube@2.0.3
+ homebridge-platform-maxcube@2.0.3
updated 1 package in 2.211s
root@homebridge:~# 

`Mai 04 17:21:16 homebridge homebridge[9745]: [4.5.2020, 17:21:16] [MaxCube Platform] Creating new accessory for Max! Link
Mai 04 17:21:17 homebridge homebridge[9745]: [4.5.2020, 17:21:17] [MaxCube Platform] Connected to Max! Cube.
Mai 04 17:21:18 homebridge homebridge[9745]: [4.5.2020, 17:21:18] [MaxCube Platform] Creating new accessory for 1 (Büro)
Mai 04 17:21:18 homebridge homebridge[9745]: [4.5.2020, 17:21:18] [MaxCube Platform] Creating new accessory for 1 (Bad)
Mai 04 17:21:18 homebridge homebridge[9745]: [4.5.2020, 17:21:18] [MaxCube Platform] Creating new accessory for Thermostat 1 (Kinderzimmer Emil)
Mai 04 17:21:18 homebridge homebridge[9745]: [4.5.2020, 17:21:18] [MaxCube Platform] Creating new accessory for 1 (Wohnzimmer)
Mai 04 17:21:19 homebridge homebridge[9745]: [4.5.2020, 17:21:19] [MaxCube Platform] Creating new accessory for Esszimmer 2 (Esszimmer)
Mai 04 17:21:19 homebridge homebridge[9745]: [4.5.2020, 17:21:19] [MaxCube Platform] Creating new accessory for 2 (Bad)
Mai 04 17:21:19 homebridge homebridge[9745]: [4.5.2020, 17:21:19] [MaxCube Platform] Creating new accessory for 1 (Küche)
Mai 04 17:21:19 homebridge homebridge[9745]: [4.5.2020, 17:21:19] [MaxCube Platform] Creating new accessory for Thermostat 1 (Kinderzimmer Paul)
Mai 04 17:21:19 homebridge homebridge[9745]: [4.5.2020, 17:21:19] [MaxCube Platform] Creating new accessory for Esszimmer 1 (Esszimmer)
Mai 04 17:21:19 homebridge homebridge[9745]: [4.5.2020, 17:21:19] [MaxCube Platform] Creating new accessory for Flur unten (Flur unten)
Mai 04 17:21:20 homebridge homebridge[9745]: [4.5.2020, 17:21:20] [MaxCube Platform] Creating new accessory for Flur oben (Flur oben)`

**Comment by marcoschmidt79** [comment]
Also dieses Mal hat er es ordentlich gemacht. :-) Direkt von 1.1.4 auf 2.0.3.

**Comment by normen** [comment]
Hm, alles klar, war wohl nicht ganz wie vorher (s.o.) aber er hat die auf jeden Fall neu erstellt und ohne doppelte UUIDs.. Tja, war wohl die Wetterlage bei Dir 😉 

Danke fürs testen und Alles Gute mit Deinem Home-Setup weiterhin!

**Comment by marcoschmidt79** [comment]
Hehe, danke dir für deine Mühe, wer weiß, was da beim ersten Mal schiefgelaufen ist.

**Comment by marcoschmidt79** [comment]
Ich habe den Fehler glaube, es lag am Update von hap-nodejs von  der Version von 0.6.9 auf 0.7.0

**Comment by normen** [comment]
Also die neuere ging dann? Nachdem Du homebridge und damit auch hap-nodejs geupdated hast? Hm ja, da tut sich grad viel bei homebridge / hap.

**Comment by normen** [comment]
Wie es aussieht kann das Problem auftreten wenn HomeBridge aus irgend einem anderen Grund beim Boot abstürzt. Das Problem ist dann dass HomeBridge nicht mehr meldet welche Geräte schon angemeldet sind aber trotzdem noch neue akzeptiert. Das führt dann dazu dass mein Plugin meint die Geräte nochmal hinzufügen zu müssen. Eher ein Problem von HB würde ich sagen, wenn er nix mehr meldet sollte er auch nix mehr annehmen..
