### ISSUE TITLE
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by normen** [normen/homebridge-platform-maxcube#23]
If homebridge crashes during boot it might still initialize the maxcube plugin but it won't report the existing devices properly. This can cause the plugin to register the accessories a second time, causing issues on the next boot.

Really homebridge shouldn't accept any new devices when it crashes so the issue itself won't be solved in this plugin.

To recover when this happens either remove `.homebridge/persist/cachedAccessories` completely or edit it in a good text editor and remove all entries that start with `"plugin": "homebridge-platform-maxcube"`. Note that the file contents are JSON but sadly its all on one line so it's quite hard to edit unless you have a text editor that can unfold the text or search the relevant sections otherwise.

**Comment by normen** [comment]
v2.0.4 should avoid this issue by waiting with the cube connection until homebridge fully booted

**Comment by IDEUSI** [comment]
hello how do I have to adjust the jason.config to use two Maxcubes?

**Comment by normen** [comment]
Hello, this is not a support forum. Please refrain from posting in random issues. The plugin supports multiple instances of the platform in config.json just like any other platform plugin for HomeBridge.

**Comment by IDEUSI** [comment]
if I want to use more than one cube the homebridge crashes
i think its a bug ?!

here my config:

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"manufacturer": "homebridge.io",
"model": "homebridge",
"port": 51826,
"pin": "031-45-154"
},
"description": "Home Smart Home",
"platforms": [
{
"name": "Config",
"port": 8080,
"auth": "form",
"theme": "dark-mode",
"restart": "sudo -n systemctl restart homebridge",
"temp": "/sys/class/thermal/thermal_zone0/temp",
"tempUnits": "c",
"lang": "auto",
"sudo": true,
"log": {
"method": "custom",
"command": "journalctl -o cat -n 500 -f -u homebridge"
},
"platform": "config"
},
{
"name": "MaxCubeUnten",
"ip": "192.168.2.82",
"port": 62910,
"windowsensor": false,
"allow_wall_thermostat": true,
"only_wall_thermostat": false,
"platform": "MaxCubePlatform"
},
{
"name": "MaxCubeOben",
"ip": "192.168.2.83",
"port": 62910,
"windowsensor": false,
"allow_wall_thermostat": true,
"only_wall_thermostat": false,
"platform": "MaxCubePlatform"
}
],
"accessories": []
}

**Comment by IDEUSI** [comment]
it still doesn't work with their latest version 2.0.7

has it really not to do with this sentence? which is shown to me as an error in the log

The dynamic platform MaxCubePlatform from the plugin homebridge-platform-maxcube seems to be configured multiple times in your config.json. This behavior was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!

**Comment by IDEUSI** [comment]
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: da3651b2-365a-49f8-91e7-40639faaa425
Mai 13 19:58:07 raspberrypi homebridge[768]:     at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
Mai 13 19:58:07 raspberrypi homebridge[768]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
Mai 13 19:58:07 raspberrypi homebridge[768]:     at Array.filter (<anonymous>)
Mai 13 19:58:07 raspberrypi homebridge[768]:     at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
Mai 13 19:58:07 raspberrypi homebridge[768]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
Mai 13 19:58:07 raspberrypi homebridge[768]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 13 19:58:07 raspberrypi homebridge[768]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mai 13 19:58:07 raspberrypi homebridge[768]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
Mai 13 19:58:07 raspberrypi homebridge[768]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
Mai 13 19:58:07 raspberrypi homebridge[768]:     at Module.load (internal/modules/cjs/loader.js:977:32)
Mai 13 19:58:07 raspberrypi homebridge[768]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
Mai 13 19:58:07 raspberrypi homebridge[768]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Mai 13 19:58:07 raspberrypi homebridge[768]:     at internal/main/run_main_module.js:18:47

**Comment by IDEUSI** [comment]
The dynamic platform MaxCubePlatform from the plugin homebridge-platform-maxcube seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!

**Comment by IDEUSI** [comment]
these are the errors I get as soon as I integrate the second cube

**Comment by IDEUSI** [comment]
020-5-13 20:07:56] [Staubsauger oben] INF changedCharging | roborock.vacuum.s5e | Robot was docked.
Mai 13 20:07:56 raspberrypi homebridge[1459]: [2020-5-13 20:07:56] [Staubsauger oben] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 104%
Mai 13 20:07:56 raspberrypi homebridge[1459]: [2020-5-13 20:07:56] [Staubsauger oben] INF changedSpeed | roborock.vacuum.s5e | Speed was changed to 104% (Max), for HomeKit 80%
Mai 13 20:08:00 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Mai 13 20:08:00 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mai 13 20:08:03 raspberrypi homebridge[1459]: [2020-5-13 20:08:03] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080
Mai 13 20:08:08 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Mai 13 20:08:08 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Mai 13 20:08:09 raspberrypi homebridge[1510]: [2020-5-13 20:08:09] Loaded config.json with 2 accessories and 4 platforms.
Mai 13 20:08:09 raspberrypi homebridge[1510]: [2020-5-13 20:08:09] ---
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Loaded plugin: homebridge-config-ui-x
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Registering platform 'homebridge-config-ui-x.config'
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] ---
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Loaded plugin: homebridge-platform-maxcube
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] ---
Mai 13 20:08:12 raspberrypi homebridge[1510]: [2020-5-13 20:08:12] Loaded plugin: homebridge-rademacher-homepilot
Mai 13 20:08:12 raspberrypi homebridge[1510]: [2020-5-13 20:08:12] Registering platform 'homebridge-rademacher-homepilot.RademacherHomePilot'
Mai 13 20:08:12 raspberrypi homebridge[1510]: [2020-5-13 20:08:12] ---
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Loaded plugin: homebridge-xiaomi-roborock-vacuum
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] ---
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Loading 4 platforms...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Config] Initializing config platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Config] Spawning homebridge-config-ui-x with PID 1539
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [RademacherHomePilot] Initializing RademacherHomePilot platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube1] Initializing MaxCubePlatform platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] The dynamic platform MaxCubePlatform from the plugin homebridge-platform-maxcube seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Initializing MaxCubePlatform platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Loading 2 accessories...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Staubsauger unten] Initializing XiaomiRoborockVacuum accessory...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Staubsauger oben] Initializing XiaomiRoborockVacuum accessory...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Thermostat2 (Büro) from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: da3651b2-365a-49f8-91e7-40639faaa425
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Array.filter (<anonymous>)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Module.load (internal/modules/cjs/loader.js:977:32)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at internal/main/run_main_module.js:18:47
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Got SIGTERM, shutting down Homebridge...
Mai 13 20:08:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Mai 13 20:08:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mai 13 20:08:22 raspberrypi homebridge[1510]: [2020-5-13 20:08:21] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080

**Comment by IDEUSI** [comment]
`020-5-13 20:07:56] [Staubsauger oben] INF changedCharging | roborock.vacuum.s5e | Robot was docked.
Mai 13 20:07:56 raspberrypi homebridge[1459]: [2020-5-13 20:07:56] [Staubsauger oben] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 104%
Mai 13 20:07:56 raspberrypi homebridge[1459]: [2020-5-13 20:07:56] [Staubsauger oben] INF changedSpeed | roborock.vacuum.s5e | Speed was changed to 104% (Max), for HomeKit 80%
Mai 13 20:08:00 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Mai 13 20:08:00 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mai 13 20:08:03 raspberrypi homebridge[1459]: [2020-5-13 20:08:03] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080
Mai 13 20:08:08 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Mai 13 20:08:08 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Mai 13 20:08:09 raspberrypi homebridge[1510]: [2020-5-13 20:08:09] Loaded config.json with 2 accessories and 4 platforms.
Mai 13 20:08:09 raspberrypi homebridge[1510]: [2020-5-13 20:08:09] ---
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Loaded plugin: homebridge-config-ui-x
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Registering platform 'homebridge-config-ui-x.config'
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] ---
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Loaded plugin: homebridge-platform-maxcube
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] ---
Mai 13 20:08:12 raspberrypi homebridge[1510]: [2020-5-13 20:08:12] Loaded plugin: homebridge-rademacher-homepilot
Mai 13 20:08:12 raspberrypi homebridge[1510]: [2020-5-13 20:08:12] Registering platform 'homebridge-rademacher-homepilot.RademacherHomePilot'
Mai 13 20:08:12 raspberrypi homebridge[1510]: [2020-5-13 20:08:12] ---
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Loaded plugin: homebridge-xiaomi-roborock-vacuum
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] ---
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Loading 4 platforms...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Config] Initializing config platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Config] Spawning homebridge-config-ui-x with PID 1539
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [RademacherHomePilot] Initializing RademacherHomePilot platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube1] Initializing MaxCubePlatform platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] The dynamic platform MaxCubePlatform from the plugin homebridge-platform-maxcube seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Initializing MaxCubePlatform platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Loading 2 accessories...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Staubsauger unten] Initializing XiaomiRoborockVacuum accessory...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Staubsauger oben] Initializing XiaomiRoborockVacuum accessory...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Thermostat2 (Büro) from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: da3651b2-365a-49f8-91e7-40639faaa425
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Array.filter (<anonymous>)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Module.load (internal/modules/cjs/loader.js:977:32)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at internal/main/run_main_module.js:18:47
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Got SIGTERM, shutting down Homebridge...
Mai 13 20:08:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Mai 13 20:08:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mai 13 20:08:22 raspberrypi homebridge[1510]: [2020-5-13 20:08:21] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080
`

**Comment by IDEUSI** [comment]
- 020-5-13 20:07:56] [Staubsauger oben] INF changedCharging | roborock.vacuum.s5e | Robot was docked.
Mai 13 20:07:56 raspberrypi homebridge[1459]: [2020-5-13 20:07:56] [Staubsauger oben] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 104%
Mai 13 20:07:56 raspberrypi homebridge[1459]: [2020-5-13 20:07:56] [Staubsauger oben] INF changedSpeed | roborock.vacuum.s5e | Speed was changed to 104% (Max), for HomeKit 80%
Mai 13 20:08:00 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Mai 13 20:08:00 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mai 13 20:08:03 raspberrypi homebridge[1459]: [2020-5-13 20:08:03] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080
Mai 13 20:08:08 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Mai 13 20:08:08 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Mai 13 20:08:09 raspberrypi homebridge[1510]: [2020-5-13 20:08:09] Loaded config.json with 2 accessories and 4 platforms.
Mai 13 20:08:09 raspberrypi homebridge[1510]: [2020-5-13 20:08:09] ---
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Loaded plugin: homebridge-config-ui-x
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Registering platform 'homebridge-config-ui-x.config'
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] ---
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Loaded plugin: homebridge-platform-maxcube
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
Mai 13 20:08:11 raspberrypi homebridge[1510]: [2020-5-13 20:08:11] ---
Mai 13 20:08:12 raspberrypi homebridge[1510]: [2020-5-13 20:08:12] Loaded plugin: homebridge-rademacher-homepilot
Mai 13 20:08:12 raspberrypi homebridge[1510]: [2020-5-13 20:08:12] Registering platform 'homebridge-rademacher-homepilot.RademacherHomePilot'
Mai 13 20:08:12 raspberrypi homebridge[1510]: [2020-5-13 20:08:12] ---
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Loaded plugin: homebridge-xiaomi-roborock-vacuum
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] ---
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Loading 4 platforms...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Config] Initializing config platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Config] Spawning homebridge-config-ui-x with PID 1539
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [RademacherHomePilot] Initializing RademacherHomePilot platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube1] Initializing MaxCubePlatform platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] The dynamic platform MaxCubePlatform from the plugin homebridge-platform-maxcube seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Initializing MaxCubePlatform platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Loading 2 accessories...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Staubsauger unten] Initializing XiaomiRoborockVacuum accessory...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Staubsauger oben] Initializing XiaomiRoborockVacuum accessory...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Thermostat2 (Büro) from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: da3651b2-365a-49f8-91e7-40639faaa425
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Array.filter (<anonymous>)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Module.load (internal/modules/cjs/loader.js:977:32)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at internal/main/run_main_module.js:18:47
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Got SIGTERM, shutting down Homebridge...
Mai 13 20:08:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Mai 13 20:08:19 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mai 13 20:08:22 raspberrypi homebridge[1510]: [2020-5-13 20:08:21] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080

**Comment by IDEUSI** [comment]
no matter what I do even if I only have one room and a termostat per cube, the homebridge crashes even after you have followed your instructions for deleting the homebridge / persist / cachedAccessories very carefully

it just does not work

**Comment by IDEUSI** [comment]
[Staubsauger unten] Initializing XiaomiRoborockVacuum accessory...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Staubsauger oben] Initializing XiaomiRoborockVacuum accessory...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Thermostat2 (Büro) from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: da3651b2-365a-49f8-91e7-40639faaa425
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Array.filter (<anonymous>)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)

**Comment by normen** [comment]
Please stay in your issue, don't fill this one with your problems and ramblings.
