### ISSUE TITLE
i have found a bug

### ISSUE THREAD

**Issue by IDEUSI** [normen/homebridge-platform-maxcube#25]
if I want to use more than one cube the homebridge crashes

here my config:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "manufacturer": "homebridge.io",
        "model": "homebridge",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "log": {
                "method": "custom",
                "command": "journalctl -o cat -n 500 -f -u homebridge"
            },
            "platform": "config"
        },
        {
            "name": "MaxCubeUnten",
            "ip": "192.168.2.82",
            "port": 62910,
            "windowsensor": false,
            "allow_wall_thermostat": true,
            "only_wall_thermostat": false,
            "platform": "MaxCubePlatform"
        },
        {
            "name": "MaxCubeOben",
            "ip": "192.168.2.83",
            "port": 62910,
            "windowsensor": false,
            "allow_wall_thermostat": true,
            "only_wall_thermostat": false,
            "platform": "MaxCubePlatform"
        }
    ],
    "accessories": []
}

**Comment by normen** [comment]
Sorry, I can't remote view your computer, you'll have to describe what software it runs, what you do and why you think it "crashed".

**Comment by IDEUSI** [comment]
Started Node.js HomeKit Server.
Mai 09 17:29:44 raspberrypi homebridge[1649]: [2020-5-9 17:29:44] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080
Mai 09 17:29:44 raspberrypi homebridge[1695]: [2020-5-9 17:29:44] Loaded config.json with 2 accessories and 4 platforms.
Mai 09 17:29:44 raspberrypi homebridge[1695]: [2020-5-9 17:29:44] ---
Mai 09 17:29:45 raspberrypi homebridge[1695]: [2020-5-9 17:29:45] Loaded plugin: homebridge-config-ui-x
Mai 09 17:29:45 raspberrypi homebridge[1695]: [2020-5-9 17:29:45] Registering platform 'homebridge-config-ui-x.config'
Mai 09 17:29:45 raspberrypi homebridge[1695]: [2020-5-9 17:29:45] ---
Mai 09 17:29:45 raspberrypi homebridge[1695]: [2020-5-9 17:29:45] Loaded plugin: homebridge-platform-maxcube
Mai 09 17:29:45 raspberrypi homebridge[1695]: [2020-5-9 17:29:45] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
Mai 09 17:29:45 raspberrypi homebridge[1695]: [2020-5-9 17:29:45] ---
Mai 09 17:29:46 raspberrypi homebridge[1695]: [2020-5-9 17:29:46] Loaded plugin: homebridge-rademacher-homepilot
Mai 09 17:29:46 raspberrypi homebridge[1695]: [2020-5-9 17:29:46] Registering platform 'homebridge-rademacher-homepilot.RademacherHomePilot'
Mai 09 17:29:46 raspberrypi homebridge[1695]: [2020-5-9 17:29:46] ---
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] Loaded plugin: homebridge-xiaomi-roborock-vacuum
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] ---
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] Loading 4 platforms...
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] [Config] Initializing config platform...
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] [Config] Spawning homebridge-config-ui-x with PID 1729
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] [RademacherHomePilot] Initializing RademacherHomePilot platform...
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] [MaxCubeOben] Initializing MaxCubePlatform platform...
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] The dynamic platform MaxCubePlatform from the plugin homebridge-platform-maxcube seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] [MaxCubeUnten] Initializing MaxCubePlatform platform...
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] Loading 2 accessories...
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] [Staubsauger unten] Initializing XiaomiRoborockVacuum accessory...
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] [Staubsauger oben] Initializing XiaomiRoborockVacuum accessory...
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] [MaxCubeUnten] Restoring Max! Link from HomeKit
Mai 09 17:29:47 raspberrypi homebridge[1695]: [2020-5-9 17:29:47] [MaxCubeUnten] Restoring Max! Link from HomeKit
Mai 09 17:29:48 raspberrypi homebridge[1695]: [2020-5-9 17:29:48] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 36810fb9-6a06-487a-b548-6f121b388031
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at Array.filter (<anonymous>)
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at Module.load (internal/modules/cjs/loader.js:977:32)
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Mai 09 17:29:48 raspberrypi homebridge[1695]:     at internal/main/run_main_module.js:18:47
Mai 09 17:29:48 raspberrypi homebridge[1695]: [2020-5-9 17:29:48] Got SIGTERM, shutting down Homebridge...
Mai 09 17:29:53 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Mai 09 17:29:53 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mai 09 17:29:55 raspberrypi homebridge[1695]: [2020-5-9 17:29:55] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080
:29:44] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8080
Mai 09 17:29:44 raspberrypi homebridge[1695]: [2020-5-9 17:29:44] Loaded config.json with 2 accessories and 4 platforms.
Mai 09 17:29:44 raspberrypi homebridge[1695]: [2020-5-9 17:29:44] ---

**Comment by normen** [comment]
Your thermostats have the same names. Rename your thermostats or the rooms they're in in the Max! software.

**Comment by IDEUSI** [comment]
all termostats and rooms have different names on both cubes nothing is double

**Comment by normen** [comment]
Right, then its probably the Max! Switch, I‘ll check that.

**Comment by IDEUSI** [comment]
and the mistake certainly has nothing to do with this sentence that is at the top?

The dynamic platform MaxCubePlatform from the plugin homebridge-platform-maxcube seems to be configured multiple times in your config.json. This behavior was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!

**Comment by IDEUSI** [comment]
no your new version dosent work with two cubes !!

**Comment by IDEUSI** [comment]
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 48ac05d2-801b-47a8-a725-b6db20f5b8e8

**Comment by normen** [comment]
No, the error has nothing to do with that. That is just a questionable idea by the HB developers but multiple platforms still work as of now.

If you already get that error when the devices are restored then it's probably stored in your device cache. You will have to remove the plugin completely once and boot homebridge to remove all max devices.
