### ISSUE TITLE
Adapter crashes in iobroker.ham 

### ISSUE THREAD

**Issue by entavio** [normen/homebridge-platform-maxcube#27]
The Adapter crashed with a lot of errors after update and restart in iobroker.ham

Caught by controller[1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
--
host.buanet-iobroker1 | 2020-05-13 17:39:38.598 | error | Caught by controller[1]: at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
host.buanet-iobroker1 | 2020-05-13 17:39:38.597 | error | Caught by controller[1]: at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
host.buanet-iobroker1 | 2020-05-13 17:39:38.597 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:103452
host.buanet-iobroker1 | 2020-05-13 17:39:38.597 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3556:25
host.buanet-iobroker1 | 2020-05-13 17:39:38.596 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.ham/main.js:177:27
host.buanet-iobroker1 | 2020-05-13 17:39:38.595 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.ham/main.js:276:39
host.buanet-iobroker1 | 2020-05-13 17:39:38.594 | error | Caught by controller[1]: at Object.start (/opt/iobroker/node_modules/iobroker.ham/lib/wrapper-handler.js:111:23)
host.buanet-iobroker1 | 2020-05-13 17:39:38.594 | error | Caught by controller[1]: at HomebridgeWrapper.init (/opt/iobroker/node_modules/homebridge-plugin-wrapper/index.js:223:17)
host.buanet-iobroker1 | 2020-05-13 17:39:38.593 | error | Caught by controller[1]: at Server.run (/opt/iobroker/node_modules/homebridge-plugin-wrapper/homebridge/server.js:93:8)
host.buanet-iobroker1 | 2020-05-13 17:39:38.593 | error | Caught by controller[1]: at Server._configCachedPlatformAccessories (/opt/iobroker/node_modules/homebridge-plugin-wrapper/homebridge/server.js:396:18)
host.buanet-iobroker1 | 2020-05-13 17:39:38.593 | error | Caught by controller[1]: at WrapperBridge.addBridgedAccessory (/opt/iobroker/node_modules/homebridge-plugin-wrapper/index.js:146:17)
host.buanet-iobroker1 | 2020-05-13 17:39:38.592 | error | Caught by controller[1]: at registerEventsForCharacteristic (/opt/iobroker/node_modules/homebridge-plugin-wrapper/index.js:136:28)
host.buanet-iobroker1 | 2020-05-13 17:39:38.592 | error | Caught by controller[1]: at Characteristic.getValue (/opt/iobroker/node_modules/homebridge-plugin-wrapper/hap-nodejs/lib/Characteristic.js:164:10)
host.buanet-iobroker1 | 2020-05-13 17:39:38.592 | error | Caught by controller[1]: at Characteristic.emit (events.js:310:20)
host.buanet-iobroker1 | 2020-05-13 17:39:38.591 | error | Caught by controller[1]: at MaxCubeLinkSwitchAccessory.getConnectionState (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-platform-maxcube/index.js:173:43)
host.buanet-iobroker1 | 2020-05-13 17:39:38.591 | error | Caught by controller[1]: TypeError: Cannot read property 'initialised' of undefined
host.buanet-iobroker1 | 2020-05-13 17:39:38.591 | error | Caught by controller[0]: [2020-5-13 17:39:35] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.

**Comment by normen** [comment]
Has nothing to do with this plugin, the name doesn't even appear in the log.

**Comment by entavio** [comment]
but i have nothing else changed....
what's about this? 

host.buanet-iobroker1 | 2020-05-13 17:39:38.591 | error | Caught by controller[1]: at MaxCubeLinkSwitchAccessory.getConnectionState (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-platform-maxcube/index.js:173:43)

**Comment by normen** [comment]
Seems like ioborker is calling devices before homebridge has booted.

**Comment by entavio** [comment]
sounds difficult and i don't know how to fix that, already tried to reinstall etc.

**Comment by entavio** [comment]
new errors


ham.0 | 2020-05-13 18:14:35.185 | error | (3153) TypeError: Cannot read property 'initialised' of undefined at MaxCubeLinkSwitchAccessory.getConnectionState (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-platform-maxcube
-- | -- | -- | --
ham.0 | 2020-05-13 18:14:35.184 | error | (3153) uncaught exception: Cannot read property 'initialised' of undefined

**Comment by normen** [comment]
Yeah, I'm on it - though as said its because iobroker is borking up the initialization. Maybe check if they didn't update the wrapper or whatever, homebridge is in heavy flux right now.

**Comment by entavio** [comment]
still using iobroker.ham in version 1.1.2. same version for the last weeks

**Comment by normen** [comment]
Yeah so ham always did it wrong. Anyway in 2.0.8 it shouldn't matter.

**Comment by entavio** [comment]
let met check that out i have to update

**Comment by entavio** [comment]
yes, adapter goes green and seems to work again :-) 
cool thx a lot
