### ISSUE TITLE
i can not add two cubes bug 2.0.0 ->2.0.8 ?!

### ISSUE THREAD

**Issue by IDEUSI** [normen/homebridge-platform-maxcube#28]
when i try to use two CUBES with the newest plugin version the whole homebridge crashes

if I take the second one out of the config everything works again !!

Where is the mistake or its a bug ?

 {
            "name": "MaxCube1",
            "ip": "192.168.2.82",
            "port": 62910,
            "windowsensor": false,
            "allow_wall_thermostat": true,
            "only_wall_thermostat": false,
            "platform": "MaxCubePlatform"
        },
        {
            "name": "MaxCube2",
            "ip": "192.168.2.83",
            "port": 62910,
            "windowsensor": false,
            "allow_wall_thermostat": true,
            "only_wall_thermostat": false,
            "platform": "MaxCubePlatform"
        }

**Comment by normen** [comment]
Please define "crash". I can't remote view your computer.

**Comment by IDEUSI** [comment]
the homebridge no longer starts

**Comment by normen** [comment]
Well without any error output or any more info I know just as much as you do.

**Comment by IDEUSI** [comment]
I get error messages in the log that a double assignment of the UUID is not possible, and so on. I still have several plugins that I use and some of them are double, but there are no errors with just two cubes

**Comment by IDEUSI** [comment]
ok wait i give you

**Comment by normen** [comment]
> I get error messages in the log that a double assignment of the UUID is not possible, and so on. I still have several plugins that I use and some of them are double, but there are no errors with just two cubes

So theres maybe multiple devices with the same name. (Like "Heater1" in both cubes)

**Comment by normen** [comment]
Also, check this: https://github.com/normen/homebridge-platform-maxcube/issues/23

**Comment by IDEUSI** [comment]
no it is not a room or a device of the same name in the rooms

**Comment by IDEUSI** [comment]
] ---
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] Loading 4 platforms...
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [Config] Initializing config platform...
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [Config] Spawning homebridge-config-ui-x with PID 2539
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [RademacherHomePilot] Initializing RademacherHomePilot platform...
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube1] Initializing MaxCubePlatform platform...
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] The dynamic platform MaxCubePlatform from the plugin homebridge-platform-maxcube seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Initializing MaxCubePlatform platform...
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] Loading 2 accessories...
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [Staubsauger unten] Initializing XiaomiRoborockVacuum accessory...
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [Staubsauger oben] Initializing XiaomiRoborockVacuum accessory...
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Aktor (Büro) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Heizung (Gäste WC) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Heizung (Büro) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Aktor (Esszimmer) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Heizung (Schlafzimmer) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Aktor 2 (Wohnzimmer) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Heizung (Badezimmer) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Aktor (Kleiderschrank) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Heizung (HWR) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Heizung (Esszimmer) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Aktor (Küche) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Aktor (Flur unten) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Heizung (Küche) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Aktor (Kinderzimmer) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Thermostat1 (test) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Thermostat2 (Büro) from HomeKit
Mai 13 19:55:22 raspberrypi homebridge[2519]: [2020-5-13 19:55:22] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 19:55:23 raspberrypi homebridge[2519]: [2020-5-13 19:55:23] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: da3651b2-365a-49f8-91e7-40639faaa425
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at Array.filter (<anonymous>)
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at Module.load (internal/modules/cjs/loader.js:977:32)
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Mai 13 19:55:23 raspberrypi homebridge[2519]:     at internal/main/run_main_module.js:18:47
Mai 13 19:55:23 raspberrypi homebridge[2519]: [2020-5-13 19:55:23] Got SIGTERM, shutting down Homebridge...

**Comment by IDEUSI** [comment]
no matter what I do even if I only have one room and a termostat per cube, the homebridge crashes even after you have followed your instructions for deleting the homebridge / persist / cachedAccessories very carefully

it just does not work

**Comment by IDEUSI** [comment]
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube1] Initializing MaxCubePlatform platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] The dynamic platform MaxCubePlatform from the plugin homebridge-platform-maxcube seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Initializing MaxCubePlatform platform...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Loading 2 accessories...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Staubsauger unten] Initializing XiaomiRoborockVacuum accessory...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [Staubsauger oben] Initializing XiaomiRoborockVacuum accessory...
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Thermostat2 (Büro) from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] [MaxCube2] Restoring Max! Link from HomeKit
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: da3651b2-365a-49f8-91e7-40639faaa425
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Array.filter (<anonymous>)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Module.load (internal/modules/cjs/loader.js:977:32)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Mai 13 20:08:14 raspberrypi homebridge[1510]:     at internal/main/run_main_module.js:18:47
Mai 13 20:08:14 raspberrypi homebridge[1510]: [2020-5-13 20:08:14] Got SIGTERM, shutting down Homebridge...
Mai 13 20:08:19 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a

**Comment by IDEUSI** [comment]
I think you speak German right?

if that is ok, i would like to make a quick phone call to explain the problem in more detail

you could call me if you like

on the phone it is much easier to isolate the problem

**Comment by normen** [comment]
No idea, looks like homebridge really can't assign the accessories properly anymore with two platforms. It passes the MaxLink twice to the MaxCube2 instance. Maybe you'll have to resort to using two cubes.

No, I won't give you phone support xD

**Comment by IDEUSI** [comment]
I want to give you support so that you can fix the bug, not the other way around. xD

and I have the cube so called cube2 its not your plugin cube 2

**Comment by IDEUSI** [comment]
it would be so much easier on the phone

I could help you to improve the plugin

**Comment by IDEUSI** [comment]
The xiaomi vacuum cleaners are also double but there is no error message so it must be due to your plugin

**Comment by IDEUSI** [comment]
its must be a problem with your plugin

**Comment by normen** [comment]
Okay pass auf, das Ding is einfach dass HomeBridge die gespeicherten Geräte nur an eine der beiden instanzen (MaxCube2) meldet. Da kann ich nix machen. Wenn die sagen dass sie es eh nicht mehr supporten ist das ja sowieso nicht der Weg.

Lass einfach nen zweiten homebridge-server auf dem Rechner laufen, die maximale Anzahl von 100 Geräten pro (home)bridge erreicht man eh schnell wenn jeder Staubsauger 10 Schalter anmeldet, dann brauchste eh ne zweiten Server. Wie gesagt nicht Gerät, einfach nochmal homebridge auf demselben Pi oder was auch immer laufen lassen.

**Comment by IDEUSI** [comment]
Ok danke

**Comment by normen** [comment]
> The xiaomi vacuum cleaners are also double but there is no error message so it must be due to your plugin

The xiaomi roborock plugin uses the "Accessory" HomeBridge type where you enter every single device manually in config.json, it's something completely different than this plugin which is a platform plugin publishing dynamic accessories.
