### ISSUE TITLE
Not an issue but an proposal for improvement - current temperature 

### ISSUE THREAD

**Issue by entavio** [normen/homebridge-platform-maxcube#29]
Hey,

is it possible to store a kind of polling function in the plugin which polls / updates the current temperature of the thermostats at regular intervals like 1 hour to get real temperature (as far as I know a change in the heating temperature is necessary) in order to provide this information e.g. to use in homekit as a temperature sensor ?!

**Comment by normen** [comment]
Yes

**Comment by entavio** [comment]
really? i mean the temperature from the heating thermostat not the wall thermostat.
 in standard or with an additional command in the config?

**Comment by normen** [comment]
"in standard"

**Comment by entavio** [comment]
but that doesn't work for me ?! the values ​​of the current temperature are only written/updatet if the target temperature is also changed  ..... 

if the thermostats are set to off, as is the case now with warm temperatures, the current temperature will never be updated again ... this is the reason why i asked about a possible function for the Update of values ​​and further use. ?!

**Comment by normen** [comment]
Does the included max! software update the temperature when the thermostats are off?

**Comment by entavio** [comment]
in the max! software the current-temperatures from the thermostats are not visible 
only the current temperatures from the wall thermostats are updated and visible

But as I said, if the plug-in will update every heating thermostat in the rhythm of e.g. 30min 
.... briefly adjust the target temperature e.g. to 10 degrees and then back to the original value you also have real-time values ​​of the current temperature without a wall thermostat

**Comment by entavio** [comment]
and it doesnt matter if the thermostat is off or on... the current temperature only updates when the target temperature is changed

**Comment by normen** [comment]
> But as I said, if the plug-in will update every heating thermostat in the rhythm of e.g. 30min
> .... briefly adjust the target temperature e.g. to 10 degrees and then back to the original value you also have real-time values ​​of the current temperature without a wall thermostat

Yeah, exactly. You can easily program that in HomeKit. As for this plugin, I don't really want to add such hacks if the standard software behaves the same.

I'd generally suggest NOT keeping the thermostats in off or manual mode as that can trigger a bug in the cube-thermostat communication after a while, requiring you to restart the thermostats to control them again. Feel free to bug ELV/EQ3 about that.
