### ISSUE TITLE
Accessory Names

### ISSUE THREAD

**Issue by htisfodrol** [normen/homebridge-platform-maxcube#30]
Hallo,
ich habe heute meine Homebridge inklusive dem "homebridge-platform-maxcube"-Plugin neu installiert. Dabei ist mir aufgefallen, dass die Namen der Thermostate und der Fenster-Kontakte nicht in Homekit übernommen werden, obwohl Homebridge die Namen richtig vom Cube übernimmt (sie werden in den Logs auch richtig angezeigt). Ich nehme an, dass liegt daran, dass keine Klammern oder Sonderzeichen in Namen mehr erlaubt sind. Das führt dazu, dass die Namen bei allen Geräten auf "Thermostat" und "Kontaktsensor", also quasi auf die Standardbezeichnungen zurückgesetzt werden.

Ist dieser Fehler schon bekannt? Ist es überhaupt einer Fehler? Ich habe es schon mit älteren Homebridge und Plugin Versionen versucht, immer mit dem gleichen Ergebnis. Eventuell liegt es ja an der neuen iOS Version 13.5.

Hi,
today I started to setup a brand new Homebridge instance (with "homebridge-platform-maxcube"-plugin) on my raspberry pi 3. I recognized that the names of the thermostats and the contact sensors are not correctly handed over to Homekit. In my Homebridge instance with "homebridge-config-ui-x"-plugin the names of the devices are correctly shown. I'm able to see the correct names in terminal logs and on the devices page of the webinterface. I guess it's maybe a problem with special characters in names (e. g. brackets). The problem causes that if I add Homebridge to Homekit the device names are only shown with their fallback names like "Thermostat" or "Contact Sensor".

Is this problem already known? Is it a problem at all? Has it maybe something to do with the new iOS version 13.5?

**Comment by normen** [comment]
Ich glaube Du hast vergessen dazu zu sagen dass Du Dir die Geräte in homebridge-config-ui-x anschaust, ne? Guck mal hier: https://github.com/oznu/homebridge-config-ui-x/issues/690

**Comment by htisfodrol** [comment]
Hallo, nein ich meine eigentlichen die Namen in Homekit.

<img width="962" alt="Terminal" src="https://user-images.githubusercontent.com/66089227/83252041-dba8b380-a1aa-11ea-9ce3-ca2d918791a0.png">
<img width="1582" alt="Geräte Config UI X" src="https://user-images.githubusercontent.com/66089227/83252063-e400ee80-a1aa-11ea-99f6-972336f6ca44.png">
<img width="787" alt="Gerät" src="https://user-images.githubusercontent.com/66089227/83252081-eb27fc80-a1aa-11ea-9a13-0ad66f2b5525.png">
<img width="566" alt="Kontakt" src="https://user-images.githubusercontent.com/66089227/83252274-40fca480-a1ab-11ea-8a0f-e50be3b48d29.png">
<img width="566" alt="Thermo" src="https://user-images.githubusercontent.com/66089227/83252288-46f28580-a1ab-11ea-974b-baf03d89199d.png">
<img width="563" alt="Fehler" src="https://user-images.githubusercontent.com/66089227/83252296-48bc4900-a1ab-11ea-8f0e-5ba126a20c60.png">

**Comment by normen** [comment]
Hm, in HomeKit war das bisher noch nicht so. Allerdings habe ich auch seit 1.1.0 die Geräte nicht mehr neu angemeldet, das letzte mal in 1.0.1. Generell würde dieses Problem - wenn es denn nicht auf Deinen Rechner beschränkt ist aus irgend einem Grund - bei mehreren Plugins auftauchen (siehe die Issue die ich oben gepostet habe). Guck' mal erst bei homebridge obs da nicht ähnliche Probleme mit anderen plugins gibt. Das "Ding" ist dass die Geräte nur einen "name" bekommen, keinen "display name" - welcher z.B. gesetzt wird wenn Du das Gerät umbenennst. Normalerweise hat HK dann immer den "name" benutzt - im Gegensatz zu config-ui-x was dann noch nie einen Namen gezeigt hat.

Und generell ist es ja ganz nett auf Deutsch zu reden, nur bringt das dem größten Teil der Internetbevölkerung gar nix.

**Comment by htisfodrol** [comment]
Okay, let's switch over to english. Thank you for your answers. I will try to find a solution for my problem. It's really hard to find out which "Thermostat" is in which room. It will be a trial and error game.

**Comment by normen** [comment]
As said, I am guessing this is a HomeKit issue, I'd suggest checking back with them.

**Comment by htisfodrol** [comment]
Okay, I will do so.

Something comes to my mind:
I have a device called "Cube / Gateway". This switch is connected to Homebridge via the Hue Bridge and the "homebridge-hue"-plugin. The name of this device was "Lightbulb" at the initial setup Homebridge in Homekit. This is maybe a hint that there is really a problem with special characters.

**Comment by normen** [comment]
Again, the issue is that the "name" is set, not the "display name" and that homekit doesn't pick up the "name" anymore (only on your computer?). It has nothing to do with special characters.

**Comment by htisfodrol** [comment]
But all other names are handed over correctly, why?

After the problem I changed the name via the Hue app to a name without the "/" and it worked (complete new setup with the official pi image + new plugin setup + new config). The name was now handed over correctly from Homebridge to Homekit. I tried it vice versa = the name was not handed over correctly.

Sorry, I don't want to argue with you. I'm not an expert, therefore it is hard to understand. And now I keep my mouth shut.

**Comment by normen** [comment]
Right, thats why I gave you the right questions to ask with the right terms. So first check if theres other similar issues over at the homebridge project, then maybe point out that devices with only a "name" and no "display name" are not shown properly anymore. Thats the best way you can help right now.

**Comment by htisfodrol** [comment]
I found a workaround the avoid the problem.

I always added Homebridge to Homekit with all devices and plugins activated, because I did a clean install. If you add Homebridge the first time, you get these setup popups where you can add the devices to the single rooms or scenes. In this popups you will always get the standard "Thermostat" and "Contact Sensor" name for each device. (I guess because of the bracket at the end of the device name.) You also get the standard name if there is a special character in the device name (like a "/"). This is not a plugin problem. All plugins I tried (Hue, Brematic, ...) have the same issues.

Workaround:
I did a complete clean install without the "homebridge-platform-maxcube"-plugin and added it to Homekit. I did the first setup in Homekit without naming problems. After I added Homebridge I installed the plugin and the Thermostats und Contact Sensors appeared in the "Standard Room" without naming problems. It's only a problem if you add the devices before you add Homebridge to Homekit.

**Comment by normen** [comment]
Very interesting and helpful, thank you very much. 🙏
