### ISSUE TITLE
Add second MacCube

### ISSUE THREAD

**Issue by UnlimitedStack** [normen/homebridge-platform-maxcube#31]
I have 2 MaxCubes, because of range problems with some devices. When I add a second plattform with different IP-Address I get an error about an already existing UUID when starting Homebridge. Is there a way to get 2 MaxCubes running?

**Comment by normen** [comment]
You have to specify a different name for each platform entry. However homebridge doesn't officially support multiple platforms in one homebridge instance anymore so there might be other issues coming up.

**Comment by UnlimitedStack** [comment]
You are right with other issues coming up, then I get the following error:

Cannot add a bridged Accessory with the same UUID as another bridged Accessory

**Comment by normen** [comment]
Well all of the single devices also have to have individual names, counting both cubes.

**Comment by UnlimitedStack** [comment]
OK, found a workarround. Just created a copy of the full plugin directory hombridge-platform-maxcube with the name home-bridge-platform-maxcube. The changed the appropiate values in **index.js** and **package.json**. Now it is loaded a second time and is working. Thank you for the hint with the different name.
