### ISSUE TITLE
[support] Which Cube responsibilities can be taken over by Homekit?

### ISSUE THREAD

**Issue by afoeder** [normen/homebridge-platform-maxcube#34]
Hi folks, hi Normen,

I use the MAX! Cube for a couple of years now in the way it is intended. At the same time I've never used Homekit or another "current" heating management solution; but very much Hue lighting and switches stuff.
I would kindly ask you to give me some guidance on what to expect. Since I never used Homekit I don't know which shortcomings are by design of Homekit, or by design of the Bridge, etc.

What I currently have (in terms of Max devices):

- Living room
  - Heating
  - Wall thermo
  - Window switch
- Bathroom
  - Heating
  - Window switch
- Kitchen
  - Heating

For the living room, I configured Cube in a way that the actual temperature is taken from the wall thermo, and when the windows are open, a lower temperature is used, of course.
Additionally, I have typical, but simple, schedules set up like "make it cozy at 17:00 [when I come home], save money from 23:00 to 5:00, heat the bathroom from 5 to 8, then save money through the day when nobody's there".

Now, what can I expect from Homekit?

Will the cube still do most of the work in terms of probing-the-temp-from-the-wall-thermo; do the cooldown when the window-switch is open, and conduct the weekly scheduling; and I have to consider Homekit just "on top" of it?

Or can/would I move some of these responsibilities to Homekit?

Sorry for the verbose description but since I am new to it, as said; I lack the knowledge of the concepts to derive it on my own.

Thanks a lot for your work!

-Adrian

**Comment by normen** [comment]
I think I explain the homebridge-platform-maxcube side of most of these things in the README, so I won't go into much detail here. Basically you should set your schedule in Max! and use HomeKit to do temporary adjustments. You can also use "manual mode" to disable the default schedule, e.g. "when the last person leaves the home".

But again, most of these things are explained in the README and HomeKit support/info is also available elsewhere.

**Comment by afoeder** [comment]
thank you @normen actually 

> Basically you should set your schedule in Max! and use HomeKit to do temporary adjustments.

is what resolves the missing link I've had. I just wasn't sure if I… miss anything.
