### ISSUE TITLE
Homebridge v. 1.3.0

### ISSUE THREAD

**Issue by crosenkr** [normen/homebridge-platform-maxcube#35]
As of omebridge v. 1.3.0., the plug-in still works but te log gives te following error: [22/02/2021, 10:02:34] [homebridge-platform-maxcube] This plugin generated a warning from the characteristic 'Status Low Battery': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.

**Comment by marcoschmidt79** [comment]
Same problem with homebridge 1.3.0 - 1.3.1-5 beta.

[22.2.2021, 20:25:21] [homebridge-platform-maxcube] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: Cannot read property 'getConnection' of undefined. See https://git.io/JtMGR for more info.

**Comment by normen** [comment]
Thanks, this is two separate issues though - @marcoschmidt79 , can you make a new issue and please add more info. Like what you run the plugin on. Sounds like thats on HOOBS or something else with a funny initialization sequence.

**Comment by normen** [comment]
The battery status issue should be fixed in 2.0.10
