### ISSUE TITLE
Error while setting temperature/mode

### ISSUE THREAD

**Issue by yesnomaybewtf** [normen/homebridge-platform-maxcube#38]
Hi,
the plugin doesnt work anymore suddenly (maybe since update to 2.0.11 today).
When i try to set a temperature oder another mode, theres an error on the console 

`2/25/2021, 3:43:38 PM] [homebridge-platform-maxcube] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: Cannot read property 'getConnection' of undefined. See https://git.io/JtMGR for more info. `
Running on the latest Homebridge in Docker.

**Comment by normen** [comment]
Can't reproduce.

**Comment by yesnomaybewtf** [comment]
Its strange. Log says Maxcube isnt reachable, along the error message
But when i try with another tool (fhem) it works.
I disabled your plugin now and use fhem to communicate with the cube.

Thank you for your work!

Von meinem iPad gesendet

**Comment by normen** [comment]
You are aware that the cube can't be accessed by multiple backends at the same time? At any instance, the error - whatever its reason - should not appear anymore in 2.0.12, the cube just wouldn't react in such a case.

**Comment by yesnomaybewtf** [comment]
Yes i know. At this point the Cube wasnt connected to homebridge or fhem.

Von meinem iPad gesendet

**Comment by normen** [comment]
🤷‍♂️ I have to restart the cube regularly no matter what software I use to control it - I guess switching to some open source 868MHz controller would be better overall. I think FHEM also has this kind of support for the EQ3 thermostats.

**Comment by yesnomaybewtf** [comment]
Fhem also communicates with the thermostats over the cube.
And yes, the cube sucks sometimes, so i connected it to a hue controlled outlet, to restart it when its not responding.

Von meinem iPad gesendet
