### ISSUE TITLE
Error Homebridge 1.3.2

### ISSUE THREAD

**Issue by marcoschmidt79** [normen/homebridge-platform-maxcube#39]
He, after update from homebridge 1.3.1 to 1.3.2 i have errors: [5.3.2021, 20:30:59] [homebridge-platform-maxcube] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 4.5. See https://git.io/JtMGR for more info.

**Comment by marcoschmidt79** [comment]
I go back to 1.3.1 and: 
[5.3.2021, 20:33:58] [MaxCube Platform] 1 (Büro) - setting mode MANUAL at temperature 4.5
[5.3.2021, 20:34:02] [MaxCube Platform] 1 (Büro) - setting temperature 21
[5.3.2021, 20:34:02] [MaxCube Platform] 1 (Büro) - setting mode AUTO at temperature 21
[5.3.2021, 20:34:19] [MaxCube Platform] 1 (Büro) - received new temperature 0

**Comment by normen** [comment]
Yeah, thats no problem, it's just a warning, not an error, you can keep using the plugin as usual. Thanks for reporting.

**Comment by marcoschmidt79** [comment]
He, the warning closing the homebridge. I restarted and after restart closing the warning the connection to max cube. After restart no connection to max cube. I going back to homebridge 1.3.1 and no problem.

**Comment by normen** [comment]
Nah, when I provoke this warning homebridge doesn't close. Must be something else thats shutting down homebridge.

**Comment by marcoschmidt79** [comment]
I have no idea. After this warning closed the connection to max cube. I open the window and the scene say max thermostat go to off.

**Comment by normen** [comment]
That is totally unrelated. Homebridge complaining about the reported value and the connection from plugin to the cube have nothing to do with each other at all. To me it simply seems that whatever you do when you update also breaks the connection to the cube for a while for some reason.

**Comment by normen** [comment]
Are you running homebridge in debug mode for some reason?

**Comment by marcoschmidt79** [comment]
Yes, i use de debug-mode for alexa-plugin. 

I have updated the max-plugin with "npm install -g".

**Comment by normen** [comment]
Hm, even in debug mode the messages just get more annoying but theres no disconnection for me.

**Comment by normen** [comment]
2.0.13 avoids those warnings - still the "error state 2" you got in the other issue hints at a "link error" in the cube.

**Comment by marcoschmidt79** [comment]
What can i do?

**Comment by normen** [comment]
Maybe log in with the Max! software? I guess the radio limit is simply reached. At any instance the warnings should be gone.
