### ISSUE TITLE
Group thermostats

### ISSUE THREAD

**Issue by satrik** [normen/homebridge-platform-maxcube#42]
Hi, 
first of all thank you for this nice plugin.
It would be a nice enhancement, to group multiple thermostats in the same room and only show 1 for the control in HomeKit.  
After a quick look, I think it should be possible according to their `room_name` or `room_id` and instead of pushing all found devices directly in the `deviceList` array, it could work to set the room_name as key and the devices as values 🤔 

Of course, there is much more to change, but do you think this can be implemented? 

greetings
satrik

**Comment by normen** [comment]
I'd like to avoid adding any logic in this layer. Theres already HomeKit and the Max software as separate entities to "configure stuff in", adding this plugin to the bunch sounds like a bad idea. Hopefully Apple adds the option to group thermostat devices just like you can group lights and switches to get the thing you want. Technically theres already loose grouping when you use Siri and e.g. say "Turn up the heating in the living room" - that should always control all heaters.
